pipeline {
    agent any

    tools {
        nodejs 'nodejs' // Ensure this matches the configured Node.js tool in Jenkins
    }

    stages {
        stage('Clone Repository') {
            steps {
                git branch: 'main', url: 'https://github.com/Sivasaikrishna19/ProfileVerse.git'
            }
        }

        stage('Install Dependencies') {
            steps {
                dir('client') { // Navigate to the client directory
                    sh 'npm install'
                }
            }
        }

        stage('Build Application') {
            steps {
                dir('client') { // Navigate to the client directory
                    sh 'npm run build'
                }
            }
        }
    }

    post {
        always {
            echo 'Pipeline completed!'
        }
        success {
            echo 'Build was successful!'
        }
        failure {
            echo 'Build failed!'
        }
    }
}
