pipeline {
    agent any

    tools {
        // Define Node.js version if installed via Jenkins Global Tool Configuration
        nodejs 'nodejs'
    }

    stages {
        stage('Clone Repository') {
            steps {
                // Checkout the source code from the repository
                git branch: 'main', url: 'https://github.com/Sivasaikrishna19/ProfileVerse'
            }
        }

        stage('Install Dependencies') {
            steps {
                // Install project dependencies using npm
                sh 'npm install'
            }
        }

        stage('Build Application') {
            steps {
                // Build the Next.js application
                sh 'npm run build'
            }
        }
    }

    post {
        always {
            echo 'Pipeline completed!'
        }
        success {
            echo 'Build was successful!'
        }
        failure {
            echo 'Build failed!'
        }
    }
}
